[package]
name = "exacting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "exacting"
crate-type = ["cdylib"]

[dependencies]
arcstr = "1.2.0"
crossbeam = "0.8.4"
pyo3 = "0.25.0"
