site_name: Exacting
site_url: https://github.com/AWeirdDev/exacting
repo_url: https://github.com/AWeirdDev/exacting
theme:
  palette:
    scheme: slate
  name: material
  icon:
    logo: material/filter
  font:
    text: Inter
    code: Roboto Mono
    heading: Inter
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AWeirdDev
      name: AWeirdDev on GitHub
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences